### ISSUE TITLE
Issue Report: /en-us/change-history

### ISSUE THREAD

**Issue by zhanyue24** [amzn/ads-advanced-tools-docs#102]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
When I try to call this API, I frequently receive a 429 too many requests error code. However, I am certain that I am making the API calls at a slow rate. Even when I wait for almost 10 minutes before attempting to call again, I still encounter the 429 error code. I'm unsure how to resolve this issue.

Request Url:  https://advertising-api.amazon.com/history
Request Boyd: 
`{
        "fromDate": 1680141792000,
        "toDate": 1687831392000,
        "count": 200,
        "sort": {
            "key": "DATE",
            "direction": "DESC"
        },
        "eventTypes": {
            "PRODUCT_TARGETING": {
                "filters": [
                    "BID_AMOUNT"
                ],
                "eventTypeIds": [
                    "224633123219965"
                ],
                "parents": [
                    {
                        "useProfileIdAdvertiser": true
                    }
                ]
            }
        }`
    
Response:
`{
        "body": {
            "message": "Too Many Requests"
        },
        "header": {
            "server": "Server",
            "date": "Tue, 27 Jun 2023 02:03:14 GMT",
            "content-type": "application/json",
            "content-length": "31",
            "connection": "keep-alive",
            "x-amz-rid": "5FT3ERKD9A201XBRB775",
            "x-amzn-requestid": "10560978-1702-4bea-b8e7-b3899fcfeda0",
            "x-amzn-errortype": "TooManyRequestsException",
            "x-amz-apigw-id": "HJ93dEztIAMF4QA=",
            "x-amzn-trace-id": "Root=1-649a4362-c2ec76b615af2e225362ddf1",
            "vary": "Content-Type,Accept-Encoding,User-Agent",
            "strict-transport-security": "max-age=47474747; includeSubDomains; preload"
        },
        "statusCode": 429,
        "errorCode": 0
    }`

**Comment by jerirose** [comment]
Hi @zhanyue24 , this is not expected behavior. 

Based on similar recent tickets in our Jira service desk, the engineering team may have resolved this in the last day, so please let us know whether you observe the same behavior now. If the problem persists, please submit an issue to the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2).
