### ISSUE TITLE
在创建sb search term报告时出错

### ISSUE THREAD

**Issue by 936447225** [amzn/ads-advanced-tools-docs#105]
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/42171091/f6ef82c4-82a8-47f5-bf55-cfa0435fc2a4)
根据文档的提示，我选择在postman请求的metrics 字段中加上query，结果提示我不对。我想问这个是什么情况，上面的箭头那里不是metrics可选的值吗。另外在关键词报告中，我需要客户的搜索词效果，query字段不确定是不是？
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/42171091/9f636eb8-58d3-49e4-8f7c-6e8ccaae4beb)

**Comment by elizafarley** [comment]
Hi @936447225, your request should **not** include `query` as a parameter, but should instead use take `query` as the `segment`. 

Example:

```
curl --request POST 'https://advertising-api.amazon.com/v2/hsa/keywords/report' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxxx' \
--header 'Amazon-Advertising-API-ClientId: xxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxx' \
--data-raw '{
"reportDate": "20211102",
"metrics": "impressions,clicks,cost",
"segment": "query",
"creativeType": "all"
}'
``` 
With this configuration, `query` is automatically added to the report.

**Comment by 936447225** [comment]
了解了 我现在已经得到了query这个字段，谢谢
