### ISSUE TITLE
Issue Report: /en-us/guides/account-management/average-daily-budget

### ISSUE THREAD

**Issue by satishaher** [amzn/ads-advanced-tools-docs#106]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
Incorrect code snippet to set isOptedOutForAverageDailyBudgetIncrease to false,
on page https://advertising.amazon.com/API/docs/en-us/guides/account-management/average-daily-budget

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/guides/account-management/average-daily-budget

**Description of what the documentation currently says**
It says 

> use [POST /accountBudgets/featureFlags](https://advertising.amazon.com/API/docs/en-us/account-budgets#/Advertiser/updateAccountBudgetFeatureFlags) and set isOptedOutForAverageDailyBudgetIncrease to false

However in code snippet from where user can copy payload it says
`
{
  "featureFlags": {
    "isOptedOutForAverageDailyBudgetIncrease": true
  }
}
`

**Description of what the documentation should say**
For code snippet it should be 
`
{
  "featureFlags": {
    "isOptedOutForAverageDailyBudgetIncrease": false
  }
}
`

**Screenshots**
<img width="1430" alt="Screenshot 2023-07-04 at 2 35 36 PM" src="https://github.com/amzn/ads-advanced-tools-docs/assets/4103047/6d2c5952-41dc-4d16-86d7-f070ab2f94ae">

**Additional context**

**Comment by jerirose** [comment]
Hi @satishaher , thank you for bringing this to our attention! That value has now been corrected.
