### ISSUE TITLE
Sponsored Display Keyword

### ISSUE THREAD

**Issue by utsavvasoya** [amzn/ads-advanced-tools-docs#109]
I am not able to find Sponsored Display keyword API for listing, creating, updating, and deleting.
As per the document SP and SB keyword API are getting but not getting SD. Can you please give me SD keyword API as soon as possible,

**Comment by elizafarley** [comment]
Hi @utsavvasoya, Sponsored Display supports two types of targeting--contextual and audience--which are different than the types of targeting for SB and SP. Keyword targeting for SD is not supported at this time. 

For more information on types of targeting supported for SD, see:

- [Contextual targeting campaigns](https://advertising.amazon.com/API/docs/en-us/guides/sponsored-display/contextual-targeting)
- [Audience targeting campaigns](https://advertising.amazon.com/API/docs/en-us/guides/sponsored-display/audience-targeting)

**Comment by elizafarley** [comment]
@utsavvasoya Let me know if you have any further questions. Resolving this issue for now.
