### ISSUE TITLE
Issue Report: /en-us/change-history

### ISSUE THREAD

**Issue by zhanyue24** [amzn/ads-advanced-tools-docs#110]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
the sponsored display type always returns empty data, but I'm certain that there is history change data for this type.

**URL of the content**
Request Url: https://advertising-api.amazon.com/history

**Comment by elizafarley** [comment]
Hi @zhanyue24, thanks for pointing out this issue. The change history API is currently only available for SP and SB--not SD. I'm working on getting the description updated to make this clear.

**Comment by zhanyue24** [comment]
Hi @elizafarley, thanks for your response. is there any plans to make SD available in the future?

**Comment by elizafarley** [comment]
@zhanyue24 I don't have any timeline at this point, but if we add support for SD, we will post in the [release notes](https://advertising.amazon.com/API/docs/en-us/release-notes/index).

**Comment by elizafarley** [comment]
The product availability for change history has now been added to the [documentation](https://advertising.amazon.com/API/docs/en-us/change-history). Resolving this issue.
