### ISSUE TITLE
campaigns post

### ISSUE THREAD

**Issue by Garnett1314** [amzn/ads-advanced-tools-docs#12]
When I do the creation of an advertising campaign：
body=[{'portfolioId': 0, 'name': '测试', 'campaignType': 'sponsoredProducts', 'targetingType': 'manual', 'state': 'paused', 'dailyBudget': 2.0, 'startDate': '20220830', 'premiumBidAdjustment': True, 'bidding': {'strategy': 'legacyForSales', 'adjustments': [{'predicate': 'placementTop', 'percentage': 0}]}}]
But it returns the error message：
[{'code': 'INVALID_ARGUMENT', 'description': "Either 'premiumBidAdjustment' or enhanced bidding controls should be specified, but not both."}]

**Comment by elizafarley** [comment]
Hi @Garnett1314 thanks for your question. Your request can only contain `premiumBidAdjustment` or the `bidding` object, not both.

Note that `premiumBidAdjustment` is a legacy feature, so we suggest using the `bidding` object to set your strategy. 
You can learn more about the different bidding strategies [here](https://advertising.amazon.com/help?#GCU2BUWJH2W3A8Z7).

You can use the following request body as an example:

```
[
  {
    "name": "Test campaign",
    "campaignType": "sponsoredProducts",
    "targetingType": "manual",
    "state": "paused",
    "dailyBudget": 2,
    "startDate": "20220830",
    "bidding": {
      "strategy": "legacyForSales",
      "adjustments": [
        {
          "predicate": "placementTop",
          "percentage": 900
        }
      ]
    }
  }
]
```
You can also omit the `bidding` object and your campaign will default to the `legacyForSales` strategy:

```
[
  {
    "name": "test campaign 3",
    "campaignType": "sponsoredProducts",
    "targetingType": "manual",
    "state": "paused",
    "dailyBudget": 2,
    "startDate": "20220830"
  }
]
```

**Comment by elizafarley** [comment]
@Garnett1314 Let me know if you have any more questions, otherwise I will close the issue. Thanks!
