### ISSUE TITLE
Issue Report: /en-us/reference/concepts/limits

### ISSUE THREAD

**Issue by XYF001** [amzn/ads-advanced-tools-docs#136]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
In the [Valid keyword characters](https://advertising.amazon.com/API/docs/en-us/reference/concepts/limits#valid-keyword-characters), the character `é` appeared twice.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/reference/concepts/limits#valid-keyword-characters

**Description of what the documentation currently says**
the character `é` appeared twice.

**Description of what the documentation should say**
Not sure, keep only one  `é`, or the second  `é` may be a typo error.

**Screenshots**
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/24812746/14fca154-9dc3-4846-9d88-5ac6caab1db9)

**Additional context**

**Comment by ramreal** [comment]
Hello - Thanks for letting us know. Will take a look!

**Comment by ramreal** [comment]
I have gone ahead and removed the duplicate character.
