### ISSUE TITLE
Issue Report: /en-us/reference/api-overview

### ISSUE THREAD

**Issue by DimaJah** [amzn/ads-advanced-tools-docs#148]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**

**URL of the content**
Provide the advanced tools center or GitHub URL where you see the bug.

**Description of what the documentation currently says**
Describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.

**Screenshots**

**Additional context**

**Comment by jerirose** [comment]
Hi @DimaJah , it looks like this is just our issue template, so I will close this issue. Please feel free to reopen and comment if you are able to let us know more about the issue!
