### ISSUE TITLE
Reporting: Sponsored Display reports v2-v3: how to specify segment tactic? (T00020, T00030)

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#169]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
It is not clear how to specify "tactic" parameter for Sponsored Display

**Description of what the documentation currently says**
There is no mention about tactic at all in V3 Reporting documentation

**Description of what the documentation should say**
I would expect documentation to expect how to deal with `tactic` parameter

**Comment by elizafarley** [comment]
Hi @wolendranh, thanks for pointing out this gap! 

In V3 reports, you no longer need to specify a tactic in the report request. Data derived from **SD campaigns of all tactics** will return in the same report in V3. I am updating the migration guide to add this note. Let me know if you have any other questions.

**Comment by elizafarley** [comment]
I've updated the [migration guide](https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/reporting-v2-v3#sponsored-display-tactic) with the above guidance. Please feel free to reopen the issue if you have any further questions.

**Comment by wolendranh** [comment]
@elizafarley Thank you for help and update of documentation! That was very helpfull!
