### ISSUE TITLE
managerAccounts limits?

### ISSUE THREAD

**Issue by maksdevit** [amzn/ads-advanced-tools-docs#17]
/managerAccounts this endpoint return max 50 linked accounts, but we have more

**Comment by jerirose** [comment]
Hi @maksdevit , thank you for alerting us to this. We are gathering info from our engineering teams and will update the OpenAPI specification if needed.

For direct support with potential workarounds on this issue, we suggest creating a Jira ticket through the [Amazon Ads API Service Desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2).

**Comment by jerirose** [comment]
Hi @maksdevit , thank you again for bringing this to our attention. This limit is now noted in the specification for [GET /managerAccounts](https://advertising.amazon.com/API/docs/en-us/reference/1-0/managerAccount#/Manager%20Accounts/getManagerAccountsForUser).

**Comment by AdsAPIPM** [comment]
@maksdevit curious if you were able to find a workaround?
