### ISSUE TITLE
Reporting V3 documentation: Sponsored product section disappeared from docs

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#170]
**Describe the bug**
There was initially v3 SP section in V3 docs, but now it is removed, right side bar menu for it also leads nowhere for SP (https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/purchased-product#sponsored-products). 
All pages (campaigns, targets etc) starts with "Configuration" headline. And are missing section for SP. Probably that Configuration is for SP? But it can be misleading. 

**Description of what the documentation should say**
Contains SP section for reports

**Screenshots**
<img width="1086" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/6746231/a86101d2-03e8-4f11-b3e6-9f26e0ed94c5">

**Comment by elizafarley** [comment]
Hi @wolendranh, can you confirm if you are still seeing this issue? I am not able to replicate on my end.

**Comment by wolendranh** [comment]
hi @elizafarley ! 

<img width="282" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/6746231/76b524c8-1fe7-42e7-9b3b-de553123b548">
Side bar section menu item "Sponsored Products" leads to nowhere, because there is no `<h2>` HTML element "Sponsored Products" where it should lead. 

Sponsored Brands, Sponsored Display, Sponsored Television all have `<h2>` heading to which sidebar points. It is not case for SP. Also missing heading element makes it confusing to understand what part of document for each report is related to SP.

**Comment by elizafarley** [comment]
Hi @wolendranh, I am able to see the Sponsored Products H2 on my end. Could you share what browser/OS are you using? 

![Screenshot 2023-11-01 at 10 00 48 AM](https://github.com/amzn/ads-advanced-tools-docs/assets/6935415/2e0dc647-f30e-4e22-8aee-3d566f4d5d83)
