### ISSUE TITLE
Ad reporting v3: missing metrics from v2 in migration guide

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#174]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
Following metrics were present in v2 reports (SD) and are missing from [migration guide](https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/reporting-v2-v3) for v2->v3 reporting:
```
attributedDetailPageView14d
viewAttributedUnitsOrdered14d
viewAttributedDetailPageView14d
viewAttributedConversions14d
viewAttributedSales14d
viewAttributedOrdersNewToBrand14d
viewAttributedSalesNewToBrand14d
viewAttributedUnitsOrderedNewToBrand14d
```

**URL of the content**
[migration guide](https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/reporting-v2-v3) for v2->v3 reporting

**Description of what the documentation currently says**
"Metric/column comparison" section of migration guide

**Description of what the documentation should say**
Please add all metrics that were present in v2 to migration table even if there is no corresponding field in v3.

**Comment by elizafarley** [comment]
Hi @wolendranh, apologies for not including these metrics initially.

They are all supported in V3. I've added them to the bottom of the mapping table here: https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/reporting-v2-v3#metrics

**Comment by wolendranh** [comment]
@elizafarley thank you! Are all v2 metrics now present in migration guide table?

**Comment by elizafarley** [comment]
I have done my best to ensure all are included. However, note that any of the V2 metrics that end in -1d, -7d, and -28d metrics are **not** included in the table because they are not supported in version 3. Version 3 only supports metrics with a 14 day attribution window for Sponsored Display.

**Comment by wolendranh** [comment]
@elizafarley hi! 

I understand that all metrics except 14d (1d, 7d etc) were removed from v3. 
But I noticed that `attributedUnitsOrdered14d` does not have corresponding field in v3. Is this expected? As it falls into `14d` fields category.

Can you confirm this?

**Comment by elizafarley** [comment]
`attributedUnitsOrdered14d` should map to `unitsSoldClicks` in V3 for both SB and SD reports. I'll update the migration guide to add that mapping.
