### ISSUE TITLE
Reporting V3 documentation: Sponsored Television - Targeting "groupBy" configuration parameter "campaigns" is not valid (should be replaced with "campaign")

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#175]
**Describe the bug**
Reporting V3 documentation: Sponsored Television - Targeting "groupBy" configuration parameter "campaigns" is not valid (should be replaced with "campaign"). 

When creating ST targeting report with "campaigns" `groupBy` configuration param API will raise exception: 
```
{"code":"400","detail":"configuration invalid groupBy values: (campaigns). Allowed values: (campaign, adGroup, targeting), '
```

So `campaigns` should be changed to `campaign`

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/targeting#sponsored-television

**Description of what the documentation should say**
`campaigns` -> `campaign`

**Screenshots**
<img width="807" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/6746231/43dc223a-6e5e-4761-bb0d-52d0b92cdc6d">

**Comment by elizafarley** [comment]
@wolendranh Thanks for calling this out! I've updated the docs to reflect the groupBy should be `campaign`. 

I really appreciate you taking the time to leave detailed feedback on the documentation!
