### ISSUE TITLE
PortfolioId in v3 SP summary keywords report is incorrect

### ISSUE THREAD

**Issue by koradiyakaushal** [amzn/ads-advanced-tools-docs#18]
**Describe the bug**
I was trying to generate the report for SP summary keywords via API is incorrect with actual productname

**URL of the content**
https://advertising-api.amazon.com/reporting/reports

**Description of what the documentation currently says**
https://advertising.amazon.com/API/docs/en-us/reporting/v3/metrics#portfolioid
The portfolio the campaign is associated with.

**Comment by elizafarley** [comment]
Hi @koradiyakaushal Could you share the request body and the error that resulted so I can better understand the issue?

**Comment by koradiyakaushal** [comment]
@elizafarley I've generated a report successfully using the steps given in the below link
https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#search-term-reports

The problem was the data, In the report, we get one field inside a report named portfolioId(https://advertising.amazon.com/API/docs/en-us/reporting/v3/metrics#portfolioId) which is incorrect

**Comment by elizafarley** [comment]
@koradiyakaushal Thanks for providing more info. It seems this may be a technical bug rather than a documentation issue. Please [open a JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) for further assistance.
