### ISSUE TITLE
Reporting API: it is not clear how to access "metrics for theme-based targets" 

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#181]
**Describe the bug**
[Documentation page](https://advertising.amazon.com/API/docs/en-us/guides/sponsored-brands/theme-based-targeting#creating-theme-based-targeting) describes Theme based targeting and there is note on how to access theme based metrics with link to keyword and search term reports. 

I checked those [pages](https://advertising.amazon.com/API/docs/en-us/guides/reporting/v2/report-types#sample-requests-5) but it is not clear what configuration and metrics should be used for these type of reports. 

From example requests it seems like requests are identical and there seems to be no theme related metrics in examples.

**URL of the content**
Provide the advanced tools center or GitHub URL where you see the bug.

**Description of what the documentation should say**
Explain how to access theme based metrics.

**Screenshots**
<img width="795" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/6746231/05855bd1-2e17-4279-ba65-82b8448ddd6d">

**Comment by ramreal** [comment]
@wolendranh - Theme targeting has no new metrics compared to the existing keyword report. It’s showed as a new entry in the report with `MatchType` as `THEME`. I will be adding a note in the documentation to make this more clear. Please let me know if you have any further questions. 

Here is an example:

```
[{
    "keywordId": 66418826413348,
    "cost": 43.51,
    "adGroupName": "Test SBVAd group 1",
    "campaignId": 52519347922011,
    "matchType": "THEME",
    "attributedSales14dSameSKU": 0,
    "attributedDetailPageViewsClicks14d": 4,
    "impressions": 26,
    "adGroupId": 262428250532707,
    "keywordText": "keywords-related-to-your-brand",
    "keywordBid": 21,
    "keywordStatus": "ENABLED",
    "campaignBudget": 100,
    "attributedConversions14d": 0,
    "campaignBudgetType": "daily",
    "campaignStatus": "enabled",
    "attributedConversions14dSameSKU": 0,
    "clicks": 5,
    "attributedSales14d": 0,
    "campaignName": "theme test 1"
}]
```
