### ISSUE TITLE
Issue Report: /en-us/guides/amazon-marketing-stream/overview

### ISSUE THREAD

**Issue by tys1128** [amzn/ads-advanced-tools-docs#186]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
AWS Workshop section's link is not found

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/guides/amazon-marketing-stream/overview#aws-workshop

**Description of what the documentation currently says**
The https://catalog.us-east-1.prod.workshops.aws/workshops/3ce6b6b0-eec1-45cc-9936-809c297900f5/en-US page shows

Page not found

The page you are looking for does not exist. You might have typed the address incorrectly or you might have used an outdated link. Please check the link and try again.

**Description of what the documentation should say**
The right content

**Screenshots**

**Additional context**

**Comment by elizafarley** [comment]
Thanks for reporting this issue! I am looking into why the link is no longer working.

**Comment by ADA-SaifShaikh** [comment]
Can you tell me which api I am getting from which campaign report I am seeing on Amazon console, I am getting wrong campaign from version 2 of api and it has migrated to version 3 because I am getting the campaign from that api. 
I get more data from the Advertising Console than from the Campaigns report

**Comment by elizafarley** [comment]
Since the workshop is no longer functional, I've removed it from the documentation. If we are able to get it working again, I'll update you here.
