### ISSUE TITLE
Recently updated api request error

### ISSUE THREAD

**Issue by niceman121** [amzn/ads-advanced-tools-docs#19]
Recently updated api request error，I have been using the previous api for over 2 years！
1. /sp/targets/bid/recommendations：
this endpoint request error 500，and cannot be improved。
2. /sp/campaigns/budget/usage：
this endpoint request error 401，But it has actually been authenticated, and calling other apis is normal

Is there a problem with the api？

**Comment by elizafarley** [comment]
Hi @niceman121 I don't see any changes to the documentation for either of the above endpoints. If you think there is a bug with the API, please [open a JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) to get assistance from our support team.
