### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mikhail-karabutov** [amzn/ads-advanced-tools-docs#191]
There are a lot of broken links in migration area
 https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/reporting-v2-v3

For example: 
[Target](https://advertising.amazon.com/en-us/guides/reporting/v2/report-types#target-reports)
[Keyword](https://advertising.amazon.com/en-us/guides/reporting/v2/report-types#keyword-reports)
[Product ad](https://advertising.amazon.com/en-us/guides/reporting/v2/report-types#product-ad-reports)
[Advertised product](https://advertising.amazon.com/en-us/guides/reporting/v3/report-types/advertised-product)

**Comment by elizafarley** [comment]
@mikhail-karabutov Thanks for reporting this. We had a bug impacting some of our links that should be resolved now.
