### ISSUE TITLE
amazon ads SB campaign report

### ISSUE THREAD

**Issue by ADA-SaifShaikh** [amzn/ads-advanced-tools-docs#192]
I get more data from the Advertising Console than from the Campaigns report
Can you tell me which api I am getting from which campaign report I am seeing on Amazon console, I am getting wrong campaign from version 2 of api and it has migrated to version 3 because I am getting the campaign from that api.

**Comment by elizafarley** [comment]
Hi @ADA-SaifShaikh, if you are seeing discrepancies between reports in the advertising console and reports in the API, I'd suggest opening a [support ticket in Jira](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2).
