### ISSUE TITLE
AD API reports v3: Gross and invalid traffic reports contains `campaignId` in example request, but it is missing from allowed metrics

### ISSUE THREAD

**Issue by wolendranh** [amzn/ads-advanced-tools-docs#198]
**Describe the bug**
AD API reports v3: Gross and invalid traffic reports contains `campaignId` in example request, but it is missing from allowed metrics. 

Actually it is not possible to request `campaignId` as for now, which makes example request misleading. But also I wanted to state that it would really make sense to allow requesting `campaignId` as otherwise it makes impossible to join this report data with other reports for some analytics and forecasting etc.

**URL of the content**
[Gross and invalid traffic report page](https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/gross-and-invalid-traffic)

**Screenshots**
<img width="646" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/6746231/4c5196c3-e973-4114-bd7e-0daff6b662cd">

**Additional context**
Please consider adding `campaignId` to Gross and invalid traffic report!

Thank you in advance!

**Comment by elizafarley** [comment]
Thanks for pointing this out! CampaignId is not supported for now. I have updated the example and will pass this feedback on to the team.
