### ISSUE TITLE
SB Keyword Create Request and Response

### ISSUE THREAD

**Issue by phatt-millips** [amzn/ads-advanced-tools-docs#203]
**Describe the bug**
It seems that the response described in the docs is incorrect. The response needs to be an array and some of the fields are incorrect when the keyword errors out.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi#tag/Keywords/operation/createKeywords

**Description of what the documentation currently says**
In the request samples section
```json
{
"keywordId": 0,
"code": "string",
"details": "string"
}
```

**Description of what the documentation should say**
```json
[{
"keywordId": 0,
"code": "string",
"description": string
"errors": List of errors
}]
```

**Comment by phatt-millips** [comment]
Edited

**Comment by phatt-millips** [comment]
Hi, this doesn't seem to be updated yet
https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi#tag/Keywords/operation/createKeywords

**Comment by ramreal** [comment]
@phatt-millips - update should be live in about 30 min.
