### ISSUE TITLE
Issue Report: /en-us/guides/sponsored-brands/targeting/negative-keyword-targeting

### ISSUE THREAD

**Issue by mauskin** [amzn/ads-advanced-tools-docs#207]
There's no description of a way to create campaign level negative keywords for Sponsored Brands.

https://advertising.amazon.com/API/docs/en-us/guides/sponsored-brands/targeting/negative-keyword-targeting

Currently page describes it as if you could only create ad group level negative keywords.
Compare that with SP page that has examples of both (https://advertising.amazon.com/API/docs/en-us/guides/sponsored-products/negative-targeting/keywords).

I would expect it to either describe both ways (campaign and ad group level) or explicitly state that only one way is possible.

**Comment by ramreal** [comment]
Hello @mauskin - thank you for letting us know! I will go ahead and update this document.

**Comment by ramreal** [comment]
This has been fixed.
