### ISSUE TITLE
Issue Report: /en-us/sponsored-brands/3-0/openapi/prod

### ISSUE THREAD

**Issue by phatt-millips** [amzn/ads-advanced-tools-docs#211]
**Describe the bug**
brandEntityId is a required field but not marked required. It should be explained why it is required and what the field represents

**URL of the content**
[Link](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod#tag/Campaigns)
 
**Description of what the documentation currently says**
"brandEntityId"

**Description of what the documentation should say**
"brandEntityId"
"Required"
<description and example of the field>

**Screenshots**
<img width="676" alt="image" src="https://github.com/amzn/ads-advanced-tools-docs/assets/23174990/ee6b40e6-ae70-49c3-bc3d-a5530df44dc8">

**Comment by elizafarley** [comment]
Hi @phatt-millips, `brandEntityId` is only required for sellers. Since not all account types require `brandEntityId` as an input, it is marked as optional in the contract. However, we can update the description to make that more clear. Thanks for calling this out!

**Comment by ramreal** [comment]
Hello @phatt-millips, description has been [updated](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod#tag/Campaigns/operation/CreateSponsoredBrandsCampaigns).
