### ISSUE TITLE
document is not work，https://advertising.amazon.com/API/docs/en-us/reference/portfolios

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#213]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
the document is not work ,i can not find it.
https://advertising.amazon.com/API/docs/en-us/reference/portfolios

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/reference/portfolios

**Description of what the documentation currently says**
https://advertising.amazon.com/API/docs/en-us/reference/portfolios

**Description of what the documentation should say**
i think this document is something about portflios update budget

![image](https://github.com/amzn/ads-advanced-tools-docs/assets/131428371/ceb9d741-b94f-4775-ba65-165a897a8e9d)

**Additional context**
https://advertising.amazon.com/API/docs/en-us/reference/portfolios

**Comment by jerirose** [comment]
Hi @CoderWeiAden , thank you for pointing this out! We've corrected the path for that specification, and the document should now be available. Please let us know if you encounter any other issues!

Note: If you already have the advanced tools center open in your web browser, you may need to clear your browser cache to see this update immediately.
