### ISSUE TITLE
how to update portfolio to noCap BudgetType ? the api of update portfolio not suport!

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#214]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
My original  portfolio budgetType was of the `DateRange`, and now I want to modify it to a type with noCap ,but the document is not enmus . How should I pass the parameters? Please provide the complete parameters and API path

**URL of the content**
My original  portfolio budgetType was of the `DateRange`, and now I want to modify it to a type with noCap ,but the document is not enmus . How should I pass the parameters? Please provide the complete parameters and API path

**Description of what the documentation currently says**
My original  portfolio budgetType was of the `DateRange`, and now I want to modify it to a type with noCap ,but the document is not enmus . How should I pass the parameters? Please provide the complete parameters and API path

**Description of what the documentation should say**
My original  portfolio budgetType was of the `DateRange`, and now I want to modify it to a type with noCap ,but the document is not enmus . How should I pass the parameters? Please provide the complete parameters and API path

**Screenshots**
PUT /v2/portfolios

**Additional context**

**Comment by elizafarley** [comment]
Hi @CoderWeiAden, the two acceptable values for portfolio budget are `monthlyRecurring` and `dateRange`. There is no option for no cap. As far as I know, there is not a way to remove a budget from a portfolio after it has been created.
