### ISSUE TITLE
Creates one or more budget rules without the campaignId info?

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#221]
when i create one budget rule for sp Campaign , i do not know how to set the campaignId for this Params
the document url is :

https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/BudgetRules/operation/CreateBudgetRulesForSPCampaigns

because the interface:  

POST
/sp/budgetRules

without campaignId ,so my request is success,but there is nothing happen,and the response is {},nothing,

please tell me how to create a budget for sp campaign ,and i wish the all params,thank you .

**Comment by ramreal** [comment]
Hello @CoderWeiAden, it seems like the only thing you need to do is associate the budget rule to the campaign. Here is a guide on how to that: https://advertising.amazon.com/API/docs/en-us/guides/rules/budget-rules/schedule-based#example-sponsored-products

**Comment by ramreal** [comment]
Thank you for submitting this issue! I will close this issue, but feel free to reopen if you have any further questions.
