### ISSUE TITLE
Issue Report: /en-us/sponsored-products/3-0/openapi/prod

### ISSUE THREAD

**Issue by baba20o** [amzn/ads-advanced-tools-docs#228]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
API web page is not loading

**URL of the content**
[Provide the advanced tools center or GitHub URL where you see the bug.](https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod)

**Description of what the documentation currently says**
Entire document wont load

**Description of what the documentation should say**
Should see the API documentation

**Screenshots**
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/42586488/a81837ee-c0ab-4bf7-b78f-881cf95f5a05)

**Additional context**

**Comment by elizafarley** [comment]
This issue has been resolved. Thanks again for reporting!
