### ISSUE TITLE
document is fail，something is wrong !!!!

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#229]
https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod

![image](https://github.com/amzn/ads-advanced-tools-docs/assets/131428371/1599aff5-3820-4e3e-897c-6503e4f8c6a4)

**Comment by elizafarley** [comment]
Hi @CoderWeiAden, thanks for reporting this. We have [another issue](https://github.com/amzn/ads-advanced-tools-docs/issues/228) tracking this issue, so I'll close this one. Please check the other issue for updates.
