### ISSUE TITLE
Issue Report: /en-us/reference/common-models/campaigns

### ISSUE THREAD

**Issue by jasonhebert** [amzn/ads-advanced-tools-docs#234]
**Describe the bug**
The documentation and examples for the Campaign common model describes an optimization object on the campaign that contains a list property called "placementBidAdjustment" but the API returns this property as "placementBidAdjustments" in the plural form.

**URL of the content**
[Provide the advanced tools center or GitHub URL where you see the bug.](https://advertising.amazon.com/API/docs/en-us/reference/common-models/campaigns#schema)

**Description of what the documentation currently says**
The schema section currently has the following paths `optimization.placementBidAdjustment.placement`, and `optimization.placementBidAdjustment.percentage`

The examples section currently shows:
```
"placementBidAdjustment": [
    {
        "placement": "string",
        "percentage": 0
    }
],
```

**Description of what the documentation should say**
The schema section should have the following paths with the plural notation `optimization.placementBidAdjustments.placement`, and `optimization.placementBidAdjustments.percentage`

The examples section should show:
```
"placementBidAdjustments": [
    {
        "placement": "string",
        "percentage": 0
    }
],
```
**Screenshots**
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/4276690/a1349914-6597-4562-8c68-145c51c5d6ff)
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/4276690/05b3f106-2b8b-4f25-8414-d71af5d9a8d1)

**Additional context**

**Comment by elizafarley** [comment]
Thanks for catching this! The documentation is incorrect in this case, and I have pushed a change to update it. It should be reflected soon.
