### ISSUE TITLE
Issue Report: /en-us/reference/common-models/enums#targetingsettings

### ISSUE THREAD

**Issue by jasonhebert** [amzn/ads-advanced-tools-docs#237]
**Describe the bug**
The documentation describes a `campaign.targetingSettings` property as an enum. The documentation lists the available values of that enum as `MANUAL` and `AUTO`. The API response objects are however returned with additional values. Currently the additional values I am receiving ar `CONTEXTUAL`, `T00020`, and `T00030`.

**URL of the content**
[https://advertising.amazon.com/API/docs/en-us/reference/common-models/enums#targetingsettings](https://advertising.amazon.com/API/docs/en-us/reference/common-models/enums#targetingsettings)

**Description of what the documentation currently says**
The section providing the definition of the TargetingSettings enum lists the accepted values for the enum.

**Description of what the documentation should say**
I am not sure if this is a documentation error or an error in the API responses.

**Screenshots**
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/4276690/074849c6-1d16-4a3f-9359-2a5c41435d25)

Example of value received from API response: 
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/4276690/b4b614c6-6419-45c8-a928-1b39d4b95d37)

**Additional context**

**Comment by elizafarley** [comment]
Hi @jasonhebert, `T00020` and `T00030` are valid responses for Sponsored Display campaigns. I will update the documentation to reflect that. `CONTEXTUAL` is not a valid response, and should instead by coming through as `T00020`. If you are seeing `CONTEXTUAL`, please open a [Jira ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) so the engineering team can investigate.

**Comment by jasonhebert** [comment]
Thank you. I'll be sure to do that if I see it (`CONTEXTUAL`) again.
