### ISSUE TITLE
ListTargetableEntities/list next Token invalid

### ISSUE THREAD

**Issue by githuabjc** [amzn/ads-advanced-tools-docs#241]
**Describe the bug**
Can't get  more response by nextToken  ads-advanced interface

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/targetable-entities#tag/TargetableEntities/operation/ListTargetableEntities
POST  /targetableEntities/list

**Description of what the documentation currently says**
when I give maxResults 1, get once resopnse ,next request I receive  response context  targetableEntities":[]
,before I give maxResults 250 ,I receive context about 51.3KB

**Description of what the documentation should say**
Why the nextToken  loss context,maybe it is document error?How can I request get the  right result

**Screenshots**
![image](https://github.com/amzn/ads-advanced-tools-docs/assets/93630206/a3d63ec9-d7e9-4d17-babf-3b9c580d532c)

**Comment by elizafarley** [comment]
@githuabjc, this seems like it might be a technical bug rather than a documentation issue. Could you create a [JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) for the support team?
