### ISSUE TITLE
Migration from adv api v2 to v3 auth. issue

### ISSUE THREAD

**Issue by FedericoSala** [amzn/ads-advanced-tools-docs#26]
Hi Amazon team,
I'm having troubles migrating our advertising api layer from v2 to v3. Basically, using the same credentials (clientId, refreshTokens and profileId), the new endpoint responses back with 401 auth error. I followed the documentation but I can't find any issues, shall I set something on the account before using the new versione?

Here's the working V2 snippet:
`headers={
    "Amazon-Advertising-API-ClientId": clientId,
    "Amazon-Advertising-API-Scope": profileId,
    "Authorization": accessToken,
    "Content-Type": "application/json"
}
data={
    "stateFilter": "enabled",
    #"metrics": metrics,
    "metrics": ",".join([ "impressions","clicks","cost","campaignId","adGroupId" ]),
    "reportDate": "20221001"
}
response = re.post("https://advertising-api-eu.amazon.com/v2/sp/productAds/report", headers=headers, json=data)
r = response.json()`

And the not working V3 snippet:
`
headers = {
    'Amazon-Advertising-API-ClientId': clientId,
    'Amazon-Advertising-API-Scope': profileId,
    'Authorization': accessToken,
    'Content-Type': 'application/vnd.createasyncreportrequest.v3+json'
}
data = {
    "name":"SP campaigns report 10/1-10/10",
    "startDate":"2022-10-01",
    "endDate":"2022-10-10",
    "configuration":{
        "adProduct":"SPONSORED_PRODUCTS",
        "groupBy":["campaign","adGroup"],
        "columns":["impressions","clicks","cost","campaignId","adGroupId","date"],
        "reportTypeId":"spCampaigns",
        "timeUnit":"DAILY",
        "format":"GZIP_JSON"
        }
    }

response = requests.post('https://advertising-api.amazon.com/reporting/reports', headers=headers, data=data)
r = response.json()
`

**Comment by jerirose** [comment]
Hi @FedericoSala , your issue may relate to the regional subdomain used in each request:
1) `https://advertising-api-eu.amazon.com` (for the working v2)
2) `https://advertising-api.amazon.com` (for the unauthorized v3)

A profile ID represents an advertiser in a single marketplace. A profile for a marketplace outside the region covered by a given host does not provide authorization for operations on the host. If the advertiser account is in EU, that profile will not be authorized on the North American host.

See [Profiles](https://advertising.amazon.com/API/docs/en-us/concepts/authorization/profiles#regions) in the advanced tools center for more information, and let us know if this helps!

**Comment by FedericoSala** [comment]
Hi @jerirose ,
what I understood from your documentation is there's just a single unified endpoint `https://advertising-api.amazon.com`, I haven't find anything about regions so far.
I literally used Amazon's docs test request with our working credentials:
`curl --location --request POST 'https://advertising-api.amazon.com/reporting/reports' \
--header 'Content-Type: application/vnd.createasyncreportrequest.v3+json' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxxx' \
--header 'Authorization: Bearer Atza|xxxxxxxxx' \
--data-raw '{
        "name":"SP targeting report 7/5-7/10",
        "startDate":"2022-07-05",
        "endDate":"2022-07-10",
        "configuration":{
            "adProduct":"SPONSORED_PRODUCTS",
            "groupBy":["targeting"],
            "columns":["adGroupId","campaignId", "targeting","keywordId","matchType","impressions", "clicks", "cost", "purchases1d", "purchases7d", "purchases14d", "purchases30d","startDate","endDate"],
            "filters": [
                {
                    "field": "keywordType",
                    "values": [
                    "TARGETING_EXPRESSION",
                    "TARGETING_EXPRESSION_PREDEFINED"
                    ]
                }
            ],
            "reportTypeId":"spTargeting",
            "timeUnit":"SUMMARY",
            "format":"GZIP_JSON"
        }
    }'`

**Comment by jerirose** [comment]
Yes, @FedericoSala , since your working v2 request is directed to `https://advertising-api-eu.amazon.com`, your v3 request using the same credentials will also need to use that same root URL.

In the example in your initial post, you could try changing this line:
```
response = requests.post('https://advertising-api.amazon.com/reporting/reports', headers=headers, data=data)
```
To this, adding `-eu` in the URL:
```
response = requests.post('https://advertising-api-eu.amazon.com/reporting/reports', headers=headers, data=data)
```

I'll also pass this on to the author of the ["Getting started" document](https://advertising.amazon.com/API/docs/en-us/reporting/v3/get-started#sample-request) to consider adding a note on regions to accompany that sample request.

**Comment by elizafarley** [comment]
I've updated the [V3 reporting tutorial](https://advertising.amazon.com/API/docs/en-us/reporting/v3/get-started) to include a note about regional URLs. Closing the issue for now.
