### ISSUE TITLE
Why is there a huge difference between the data on both sides of the sd report type obtained through the "v3 report" API interface and the report exported from the seller center?

### ISSUE THREAD

**Issue by xuqiang97** [amzn/ads-advanced-tools-docs#265]
Why is there a huge difference between the data on both sides of the sd report type obtained through the "v3 report" API interface and the report exported from the seller center?

such as this sd report type：
api：
https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/advertised-product
reportTypeId：sdAdvertisedProduct
seller center：
Report category：Sponsored Display
Report type：Advertised product

If you need me to provide more information such as MerchantId or API requestId, please contact me. Thank you for your support!

**Comment by xuqiang97** [comment]
**@elizafarley hi, I need you help!  Thank you in advance for your support!**

**Comment by elizafarley** [comment]
@xuqiang97, In this case, I would recommend reaching out to our support team (ads-api-support@amazon.com) so they can look into your specific case.
