### ISSUE TITLE
Issue Report: /en-us/guides/reporting/v3/report-types/audio-and-video

### ISSUE THREAD

**Issue by IgniteMosquito** [amzn/ads-advanced-tools-docs#267]
**Describe the bug**
Group by specification is inconsistent.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/audio-and-video

**Description of what the documentation currently says**
 Table vs. list of additional fields have different group by parameters. Group by ad vs. group by lineitem.

**Comment by glmcmull** [comment]
Thanks for the report! Should be fixed now -- the group bys in the sidebar were correct, must have not noticed since 'lineitem' and 'order' were the previous names for these resources, so it was easy to glance over.
