### ISSUE TITLE
Amazon ads API

### ISSUE THREAD

**Issue by Ganjamaicart** [amzn/ads-advanced-tools-docs#272]
[Amazon_Ads_API_Environment.postman_environment.json](https://github.com/amzn/ads-advanced-tools-docs/files/15408574/Amazon_Ads_API_Environment.postman_environment.json)
How do I imort the Postman environment and  collection in github?

**Type of content**
[ ] Advanced tools center documentation
[ ] Amazon Ads API Postman collection
[ ] Other

**Describe the solution you'd like**

**Additional context**
Add any relevant URLs or other context about the problem here.

**Comment by jerirose** [comment]
Hi @Ganjamaicart , links to setup instructions can be found in the ["Setup" section](https://github.com/amzn/ads-advanced-tools-docs/tree/main/postman#setup). I'll post that content here as well:

> To use the collection, you will need credentials for the Amazon Ads API. For information about acquiring credentials, see the [onboarding overview for the Amazon Ads API](https://advertising.amazon.com/API/docs/en-us/setting-up/overview).
>
> Find setup instructions in the Amazon Ads advanced tools center for:
>
> - [New users of the Amazon Ads API](https://advertising.amazon.com/API/docs/en-us/getting-started/using-postman-collection)
> - [Users with an existing refresh token](https://advertising.amazon.com/API/docs/en-us/tutorials/postman)
>
> You can also view a [video walkthrough of the collection setup steps on YouTube](https://www.youtube.com/watch?v=SWqOPN33phw).
