### ISSUE TITLE
sp campaign update the end date is fail 

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#273]
i have he sp campaign ,and it have startDate(2024-07-01) and endDate(2024-07-05)，
now i want to update the sp campaign without endDate,
my param is :
{"campaigns":[{"budget":{"budget":2,"budgetType":"DAILY"},"campaignId":"369356990030083","dynamicBidding":{"placementBidding":[{"percentage":0,"placement":"PLACEMENT_TOP"},{"percentage":0,"placement":"PLACEMENT_PRODUCT_PAGE"},{"percentage":0,"placement":"PLACEMENT_REST_OF_SEARCH"}],"strategy":"LEGACY_FOR_SALES"},"name":"HFX3XL-sp-adentest0523","startDate":"2024-06-12","state":"PAUSED","tags":{"property1":"{\"businessId\":\"2128\"}"}}]}

and it have not endDate ,but don`t update the campain endDate actually，

and i try to set the endDate is empty string ,like ''  ,but it does`t work ,

so how can i set the campaign endDate to null

**Comment by kdwivedi13** [comment]
To remove or clear the endDate for a campaign, you can try including "endDate": null in the request payload when updating the campaign.
