### ISSUE TITLE
Clarify Uniqueness of IDs

### ISSUE THREAD

**Issue by rabbiveesh** [amzn/ads-advanced-tools-docs#28]
**Type of content**
[X] Advanced tools center documentation

**Describe the solution you'd like**
In the [Developer Notes section on Object IDs](https://advertising.amazon.com/API/docs/en-us/info/developer-notes#object-ids), it states that IDs are unique for each type. I understand that it means that if I have an `adId`, I can be sure that no other ad has the same ID, though an `adGroup` or `campaign` could.
What is a drop ambiguous is if these are unique globally, or only per ad product. Meaning, can a Sponsored Brands ad have the same `adId` as a Sponsored Products ad?

**Comment by elizafarley** [comment]
Hi @rabbiveesh, thanks for pointing this out. 

In more detail, object IDs are distinct within the same marketplace/profile. Campaign IDs across all ad types will be unique if they belong to the same profile. However, you could see duplication of IDs within different marketplaces/profiles. For example, you could see a US campaign ID repeated in the UK marketplace.

Let me know if that answers your question, and I'll work on getting the documentation updated to reflect this.

**Comment by rabbiveesh** [comment]
Wow, I actually wasn't expecting that. Thank you so much, that does answer my question.

Can we keep this open until the docs are updated?

**Comment by rabbiveesh** [comment]
Also @elizafarley , from what you wrote it implies that Profile IDs are only unique within a particular marketplace. So that means that in theory in Canada and the US, two different acounts can have the same profile ID?

**Comment by elizafarley** [comment]
Happy to help! Profile IDs are globally unique, so you won't see the same profile ID used across regions. We will also include that in the doc updates. I'll post a link to the updates here once we've made them.

**Comment by elizafarley** [comment]
To follow up, I've updated the [Developer notes](https://advertising.amazon.com/API/docs/en-us/info/developer-notes) to expand on uniqueness for object IDs. Hopefully this helps clarify. I'll close the issue, but please follow up with any further questions!
