### ISSUE TITLE
Some issues regarding promotions

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#286]
Hi Amazon GitHub Team,
I'm sorry to raise an issue in this project because I can't find the corresponding project to raise an issue。

I hope you're having a fantastic day! I'm currently working on an integration project and have a few questions regarding the creation of various promotions. Specifically, I would like to know the available methods for creating the following types of promotions:

Coupon
Best Deal
Price Discount
Promo Code
Lightning Deal
Could you please provide information on the following:

APIs: Are there any APIs available for creating these promotions?
Data Streams: Is it possible to use data streams for this purpose? If so, could you provide details on how to implement this?
Message Listeners: Are there any message listener services that can be used for creating these promotions?
Other Methods: If there are any other recommended methods for achieving this, please let me know.
Any relevant documentation, examples, or resources would be greatly appreciated.

Thank you for your assistance!

Best regards,
Aden, the newbie coder exploring the vast Amazon ecosystem

**Comment by elizafarley** [comment]
Hi @CoderWeiAden, the use cases described above are not available via the Amazon Ads API (which is the scope of this GitHub repository). If available, these features would be supported by the [Amazon Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/welcome). 

In particular, the [Product Pricing API](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide) may fit this use case.
