### ISSUE TITLE
Issue Report: /sp/campaigns/list

### ISSUE THREAD

**Issue by xiaozhong1995** [amzn/ads-advanced-tools-docs#287]
hello.

I use [/sp/campaigns/list](https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Campaigns/operation/DeleteSponsoredProductsCampaigns) for pagination query activities, but when the number of entries exceeds 500, an error will be reported. Whether it is a one-time query or multiple queries, as long as the total number exceeds 500, an error will be reported, as shown below:

{"code":"INTERNAL_ERROR","message":"Service Error"}

**Comment by elizafarley** [comment]
Hi @xiaozhong1995, this seems like a technical bug rather than a documentation issue. Please open a support ticket in [Zen Desk](https://amazon-ads-api.zendesk.com/hc/en-us) for further assistance.
