### ISSUE TITLE
sp campaign update interface error

### ISSUE THREAD

**Issue by CoderWeiAden** [amzn/ads-advanced-tools-docs#290]
The original campaign data has the same start date and end date:
{
    "campaigns": [
        {
            "campaignId": "296750104888300",
            "portfolioId": "57472928093112",
            "endDate": "2024-08-03",
            "name": "HFX3XL-sp-ewqrewtyury",
            "targetingType": null,
            "state": "ENABLED",
            "dynamicBidding": null,
            "startDate": "2024-08-03",
            "budget": {
                "budgetType": "DAILY",
                "budget": 12.00
            },
            "tags": null
        }
    ]
}

set the campaign endDate to null ,and the target data after modification is changed to have no end date,the param is :
{
    "campaigns": [
        {
            "campaignId": "296750104888300",
            "portfolioId": "57472928093112",
            "endDate": null,
            "name": "HFX3XL-sp-ewqrewtyury",
            "targetingType": null,
            "state": "ENABLED",
            "dynamicBidding": null,
            "startDate": "2024-08-03",
            "budget": {
                "budgetType": "DAILY",
                "budget": 12.00
            },
            "tags": null
        }
    ]
}

However, the API returns an error:
"Start date cannot be after end date."

**Comment by elizafarley** [comment]
HI @CoderWeiAden this seems like it could be a technical bug. I'd recommend opening a [support ticket](https://advertising.amazon.com/API/docs/en-us/support/overview) if you are still seeing this issue.
