### ISSUE TITLE
Issue Report: /en-us/guides/reporting/dsp/metrics offAmazonCPA14d and offAmazonCVR14d flipped

### ISSUE THREAD

**Issue by jesgueva** [amzn/ads-advanced-tools-docs#296]
**Describe the bug**
The descriptions of offAmazonCPA14d and offAmazonCVR14d are flipped.

**URL of the content**
[Provide the advanced tools center or GitHub URL where you see the bug.](https://advertising.amazon.com/API/docs/en-us/guides/reporting/dsp/metrics)

**Description of what the documentation currently says**
offAmazonCPA14d
Type: Decimal

Description: The number of Off-Amazon conversions relative to the number of ad impressions. (Off-Amazon CVR = Off-Amazon / Impressions)

Report types: [Campaign](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#campaign), [Inventory](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#inventory), [Audience](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#audience)

offAmazonCVR14d
Type: Percentage

Description: The average cost to acquire an Off-Amazon conversion. (Off-Amazon CPA = Total cost / Off-Amazon)

Report types: [Campaign](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#campaign), [Inventory](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#inventory), [Audience](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#audience)

**Description of what the documentation should say**
offAmazonCVR14d
Type: Percentage

Description: The number of Off-Amazon conversions relative to the number of ad impressions. (Off-Amazon CVR = Off-Amazon / Impressions)

Report types: [Campaign](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#campaign), [Inventory](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#inventory), [Audience](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#audience)

offAmazonCPA14d
Type: Decimal

Description: The average cost to acquire an Off-Amazon conversion. (Off-Amazon CPA = Total cost / Off-Amazon)

Report types: [Campaign](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#campaign), [Inventory](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#inventory), [Audience](https://advertising.amazon.com/API/docs/en-us/reporting/dsp/report-types#audience)

**Comment by glmcmull** [comment]
Thanks for the report. We'll address this bug as soon as we can.

**Comment by glmcmull** [comment]
Thanks for the report! This fix will be live tonight at 12AM est.
