### ISSUE TITLE
Request for API Endpoint to Access Client Ad Console

### ISSUE THREAD

**Issue by AlexUnitix** [amzn/ads-advanced-tools-docs#303]
Hello,

I need to obtain a link to the clients' ad console so that we can directly access it from our software. Could you please guide me on how to achieve this using the Amazon Ads API? Is there a specific endpoint or method that allows us to retrieve such a link?

**Comment by ramreal** [comment]
Hello @AlexUnitix ,

Thank you for contacting us. There is currently no link in regards to retrieving a link. I can forward this information to our engineering team to propose this enhancement in the future. If you have any further questions, feel free to reopen issue.
