### ISSUE TITLE
Issue Report: Could not find resource for full path: http://advertising-api.amazon.com/sb/v4/campaigns

### ISSUE THREAD

**Issue by xiaokang086888** [amzn/ads-advanced-tools-docs#310]
PUT https://advertising-api.amazon.com/sb/v4/campaigns   [
  {
    "campaignId": 144147368340394165,
    "state": "enabled"
  }
] 
 
 Response:
 404
{"code":"NOT_FOUND","details":"Could not find resource for full path: http://advertising-api.amazon.com/sb/v4/campaigns"}

**Comment by ramreal** [comment]
Hello @xiaokang086888 , based on the example you provided, it looks like the `h` in https is missing. Also be sure to have content-type as `application/vnd.sbcampaignresource.v4+json`

Here is a sample request:

`curl --location --request PUT 'https://advertising-api.amazon.com/sb/v4/campaigns' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxx' \
--header 'Authorization: Bearer Atza|xxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxx' \
--header 'Accept: application/vnd.updatecampaignsresponse.v4+json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "campaigns": [
        {
            "bidding": {
                "bidOptimization": true
            },
            "campaignId": "553554267190715",
            "name": "string",
            "state": "ENABLED",
            "startDate": "2023-06-15",
            "budget": 100
        }
    ]
}'`

**Comment by xiaokang086888** [comment]
Thanks for update, still doesn't work. 

 PUT https://advertising-api.amazon.com/sb/v4/campaigns   {
  "campaigns": [
    {
      "campaignId": "144147368340394165",
      "state": "ENABLED"
    }
  ]
}

{"code":"NOT_FOUND","details":"Could not find resource for full path: http://advertising-api.amazon.com/sb/v4/campaigns"}

**Comment by xiaokang086888** [comment]
curl --location --request PUT https://advertising-api.amazon.com/sb/v4/campaigns  --header "Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.11" --header "Authorization:Bearer Atza|11111" --header "Amazon-Advertising-API-Scope:111" --data-raw "{"campaigns":[{"campaignId":"144147368340394165","state":"ENABLED"}]}"

{"code":"NOT_FOUND","details":"Could not find resource for full path: http://advertising-api.amazon.com/sb/v4/campaigns"}

**Comment by xiaokang086888** [comment]
I find the reason as follow, 
If missing the header 'Accept: application/vnd.updatecampaignsresponse.v4+json', or set to "application/json", will get error "{"code":"NOT_FOUND","details":"Could not find resource for full path: [http://advertising-api.amazon.com/sb/v4/campaigns"}](http://advertising-api.amazon.com/sb/v4/campaigns%22%7D)"

So please make sure it's correct.

By the way, the response message is misunderstanding.
