### ISSUE TITLE
Incomplete curl statement - marketing stream documentation

### ISSUE THREAD

**Issue by PatDotter** [amzn/ads-advanced-tools-docs#37]
**Describe the bug**
One of the sample curl statements is incomplete and there are some typos in the statement too.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/managing-subscriptions#sample

**Description of what the documentation currently says**
```
curl —location —request GET '/streams/subscriptions?maxResults=10'\
--header'Amazon-Advertising-API-ClientId: xxxxxxxxx' \
--header'Amazon-Advertising-API-Scope: xxxxxxxx' \ 
```

**Description of what the documentation should say**
```
curl --location --request GET 'https://advertising-api.amazon.com/streams/subscriptions?maxResults=10' \
--header 'Amazon-Advertising-API-ClientId: xxxxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxxxx' \
--header 'Authorization: Bearer xxxxxxxxx'
```

**Screenshots**
**pic 1**
![Screenshot from 2022-11-28 15-13-44](https://user-images.githubusercontent.com/59281122/204299256-d6d7dbea-cfee-479b-b0c9-38fca8c13a57.png)

**pic 2**
![Screenshot from 2022-11-28 15-06-00](https://user-images.githubusercontent.com/59281122/204298928-7b2cad8c-2769-4d2a-b9ba-bcae074d6ed9.png)

**Additional context**
I don't know anymore if every change i made was necessary, but it was working in the end.

**Comment by elizafarley** [comment]
@PatDotter Thanks for pointing this out! I've [updated the docs](https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#sample-calls) with a complete sample.
