### ISSUE TITLE
Missing docs for portfolio real-time budget usage

### ISSUE THREAD

**Issue by mkaay** [amzn/ads-advanced-tools-docs#4]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
Missing docs for portfolio real-time budget usage.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/info/release-notes#budget-usage-percentage-now-available-for-real-time-pulls-in-amazon-ads-api

**Description of what the documentation currently says**
"You can pull budget usage information for both campaigns and **portfolios**."

**Description of what the documentation should say**
Link to information how to pull live budget usage for portfolios.

**Screenshots**

**Additional context**
Nothing to be found in the portfolio docs.
https://advertising.amazon.com/API/docs/en-us/reference/2/portfolios#/Portfolios

**Comment by ptaylor9999** [comment]
@mkaay Thank you for opening the issue, this is now fixed:

[Portfolio Budget Usage](https://advertising.amazon.com/API/docs/en-us/reference/portfolios#/Budget%20Usage)

**Comment by mkaay** [comment]
Thanks!
