### ISSUE TITLE
Product targeting 415

### ISSUE THREAD

**Issue by andanyoung** [amzn/ads-advanced-tools-docs#41]
![image](https://user-images.githubusercontent.com/13751605/211268124-c47ba084-6794-44d1-bdac-ef7107336b2e.png)

![image](https://user-images.githubusercontent.com/13751605/211268427-50ddd0ea-3373-4f1d-ad85-cc27ac00550f.png)

`application/vnd.sblisttargetsresponse.v3+json`  is 415 `Cannot consume content type`

What this header ?

**Comment by elizafarley** [comment]
Hi @andanyoung, can you try the request using both the Accept and Content-Type headers as shown in the cURL example below?

```
curl --location --request POST 'https://advertising-api.amazon.com/sb/targets/list' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxxxxxx' \
--header 'Authorization: Bearer xxxxxxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxxxxxxxxx' \
--header 'Accept: application/vnd.sblisttargetsresponse.v3+json' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```

**Comment by elizafarley** [comment]
@andanyoung Were you able to successfully call the endpoint? Let me know if you are still having issues, otherwise I'll close the ticket.

**Comment by andanyoung** [comment]
This right `--header 'Content-Type: application/json' ` , not `--header 'Content-Type: application/vnd.sblisttargetsresponse.v3+json' `

![image](https://user-images.githubusercontent.com/13751605/212446116-7c8f0652-4085-42d7-a4c4-c29c934b1bcd.png)
