### ISSUE TITLE
How to create SQS queues with amazon marketing stream datasetId of sponsored-ads-campaign-diagnostics-recommendations and retail-sales-metrics

### ISSUE THREAD

**Issue by lynmison** [amzn/ads-advanced-tools-docs#44]
Hi elizafarley 
    When we create subscription, datasetId includes  sp-conversion, sp-traffic, budget-usage, sd-traffic, sd-conversion, sponsored-ads-campaign-diagnostics-recommendations and retail-sales-metrics, but https://github.com/amzn/ads-advanced-tools-docs/blob/main/amazon_marketing_stream/Stream_SQS%20_CF_Template.yaml only includes 4 queues (sp-conversion, sp-traffic, budget-usage, sd-traffic, sd-conversion). How to create SQS queues with campaign-diagnostics-recommendations and retail-sales-metrics ?

**Additional context**

- Amazon ads document. [https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/openapi#/Stream%20Subscription/CreateStreamSubscription](url)
- Amazon Marketing Stream data guide. [https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/data-guide](url)

thanks and hope for your reply :)

**Comment by elizafarley** [comment]
Hi @lynmison, sorry for the confusion here. The `sponsored-ads-campaign-diagnostics-recommendations` and `retail-sales-metrics` datasets are currently in preview, and not yet generally available. I am working with the product team update the API documentation to mark those datasetIds as preview only.

When those new datasets become available, we will post in the [release notes](https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/release-notes).

**Comment by lynmison** [comment]
> Hi @lynmison, sorry for the confusion here. The `sponsored-ads-campaign-diagnostics-recommendations` and `retail-sales-metrics` datasets are currently in preview, and not yet generally available. I am working with the product team update the API documentation to mark those datasetIds as preview only.
> 
> When those new datasets become available, we will post in the [release notes](https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/release-notes).

Copy that, many thanks for your kindly reply.

**Comment by elizafarley** [comment]
This has been reflected in the [docs](https://github.com/amzn/ads-advanced-tools-docs/issues/url). Resolving.
