### ISSUE TITLE
Typo in Documentation for Amazon Marketing Stream sp-conversion data

### ISSUE THREAD

**Issue by PatDotter** [amzn/ads-advanced-tools-docs#45]
In the Data guide of the Amazon Marketing Stream for the sp-conversion fields for the dataset_id its written the value would be sp-traffic instead of sp-conversion.

**URL of the content**
[Amazon Marketing Stream sp-conversion data docs](https://advertising.amazon.com/API/docs/en-us/amazon-marketing-stream/data-guide#sponsored-products-conversions-sp-conversion)

**Screenshots**
![image](https://user-images.githubusercontent.com/59281122/220112961-123cc797-b956-4769-9218-df3dd6c39bd3.png)

**Comment by elizafarley** [comment]
@PatDotter thanks for pointing this out. It's a typo and should be sp-conversion in this description. I'm pushing a fix for this that should be reflected shortly.

**Comment by elizafarley** [comment]
This change is live. Resolving!
