### ISSUE TITLE
Cannot submit the application form for accessing the Amazon advertising API

### ISSUE THREAD

**Issue by jiwei3187553** [amzn/ads-advanced-tools-docs#51]
We wish to access the amazon advertising API and we follow the steps in this [link](https://advertising.amazon.com/API/docs/en-us/setting-up/step-2-complete-application) to apply as a partner. However when we tried to submit an application we encountered an error that says,

Please ensure that you are signed into the Amazon account affiliated with your corporate email address. If you do not have an Amazon account affiliated with your corporate email address, you may update your current Amazon account or create an account

We have tried various accounts and email addresses affiliated with Amazon but it still produces the same error. I don't understand what corporate email address are they referring to. How do we resolve this?
![微信截图_20230228153457](https://user-images.githubusercontent.com/25273864/224622017-afb2e2e6-3d7c-4bf9-ab84-7ed6f936c76c.png)

**Comment by jerirose** [comment]
For issues registering with the Partner Network, take a look at the [Partner Network help center content on registration](https://advertising.amazon.com/partner-network/help/GEBCGKXA5SGBSQ59). 

If those answers don't help to resolve the problem, contact the Partner Network team directly using their ["contact us" intake form](https://advertising.amazon.com/partner-network/contact).
