### ISSUE TITLE
[createCampaign API] has incorrect inclusion of "budget" in the required fields

### ISSUE THREAD

**Issue by harinsp** [amzn/ads-advanced-tools-docs#52]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**
https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi#/Campaigns/createCampaigns
The createCampaign API  endpoint (/sd/Campaigns) currently says 
Required fields are name, tactic, state, budget, and startDate. 

<img width="1504" alt="Screenshot 2023-03-13 at 10 23 41 AM" src="https://user-images.githubusercontent.com/127762455/224731531-2de68243-8736-4306-91a3-9b2ed6af9270.png">

But, as an API user I can create a campaign without budget. (refer to the screenshot below, where I could create a campaign without specifying **budget**) 

<img width="899" alt="Screenshot 2023-03-13 at 10 38 33 AM" src="https://user-images.githubusercontent.com/127762455/224734230-04d69f9e-4134-44a1-9218-9dd687e9dea3.png">

Reason: If the budget parameter is not specified in the request body, then a default budget automatically gets assigned to it during campaign creation. 

Expected: 
The documentation should be updated to say 
Required fields are name, tactic, state, and startDate. (because budget is really not a required json field)

**Comment by elizafarley** [comment]
HI @harinsp, thanks for pointing this out. As you noted, `budget` should not be marked as required. For USD, the default budget is $100. We'll be updating the contract and publishing a table of default budget by region shortly. I'll comment here once it's live.

**Comment by harinsp** [comment]
Hi @elizafarley  - awesome. Thank you for updating it.

**Comment by elizafarley** [comment]
This should be fixed in the documentation now! I've updated the contract and added [this table](https://advertising.amazon.com/API/docs/en-us/concepts/limits#default-budgets) with the default budgets based on region.
