### ISSUE TITLE
Issue Report: /en-us/reporting/v2/report-types

### ISSUE THREAD

**Issue by pomelo-tech** [amzn/ads-advanced-tools-docs#53]
**Describe the bug**
can not get currency from keywords sponsored brands report by using version2 report api

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#keyword-reports

**Description of what the documentation currently says**
![image](https://user-images.githubusercontent.com/65641411/225266148-8b0e148f-bdc7-45d0-a30e-bb4361e977d2.png)

**Additional context**

**Comment by elizafarley** [comment]
Hi @pomelo-tech,

Is the request failing for you, or are you just not receiving a value for currency in the report itself? 

This request is working for me:

```
curl --location 'https://advertising-api.amazon.com/v2/hsa/keywords/report' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer Atza|xxxxxxxx' \
--data '{
    "reportDate":"20230310",
    "metrics":"campaignId,adGroupId,currency",
    "creativeType":"all"
}'
```

**Comment by elizafarley** [comment]
Hi @pomelo-tech, please let us know if this helped or if you are still having an issue. Otherwise we will close the issue for now.
