### ISSUE TITLE
Typo Error in Requesting reports page

### ISSUE THREAD

**Issue by JaehyunAhn** [amzn/ads-advanced-tools-docs#6]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**

There is Typo in Requesting Reports page

**URL of the content**

https://advertising.amazon.com/API/docs/en-us/tutorials/sponsored-ads-reports#requesting-reports

**Description of what the documentation currently says**

From: "POST /v2/hsa/{recordType/report"

**Description of what the documentation should say**

To: "POST /v2/hsa/{recordType}/report"

Close middle size braket needed

**Comment by elizafarley** [comment]
Thanks for pointing this out! I've fixed it in the documentation.
