### ISSUE TITLE
Issue Report: /en-us/bulksheets/2-0/create-sb-campaign

### ISSUE THREAD

**Issue by gamboapaolo** [amzn/ads-advanced-tools-docs#64]
### **Describe the bug**
Create: SB Campaign.
2nd Step - Keyword Entity
Duplicate Rows:
- Brand Name*
- Brand Logo Asset Id*
- Brand Logo URL
- Creative Headline*
- Creative asins*
- Video Media Ids
- Creative Type*

### **URL of the content**
https://advertising.amazon.com/API/docs/en-us/bulksheets/2-0/create-sb-campaign#step-2a-define-the-keyword-entity-object-object-

### **Description of what the documentation should say**
As I understand, the last row should be "Creative Type*".

### **Screenshots**
![image](https://user-images.githubusercontent.com/62457743/229076568-5160ab8b-b644-42af-a187-f055825f9fb5.png)

**Comment by DrRockett** [comment]
Hi! Updating to let you know [this document has been updated](https://advertising.amazon.com/API/docs/en-us/bulksheets/2-0/create-sb-campaign#step-2a-define-the-keyword-entity-object-object-)--thank you again for reporting this!
