### ISSUE TITLE
Advertised product reports Issue

### ISSUE THREAD

**Issue by tonisantes** [amzn/ads-advanced-tools-docs#73]
Hello,
I'm migrating from v2 to v3 and I was able to successfully generate the Advertised product reports but I noticed that the report did not include paused campaigns. Then I checked the documentation [here](https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#group-by-advertiser) and figured I could use the `campaignStatus` filter to include paused campaigns, but then I got this error:

> configuration filters includes fields: (campaignStatus) which are invalid for groupBys: advertiser. 
Allowed filters for groupBy advertiser: (field: adCreativeStatus, values: ENABLED, PAUSED, 'ARCHIVED)

Then I tried using the `adCreativeStatus` filter, it successfully generated the report but didn't include paused campaigns either.

Seems like a bug to me, but if not, how can I include paused campaigns in the report?

**Comment by elizafarley** [comment]
Thanks for pointing this out! It definitely appears we have a bug in the documentation, so I'll work on getting that fixed. I'm also looking into what the expected behavior is with the team and will update you when I have an answer.

**Comment by elizafarley** [comment]
@tonisantes Could you [open a JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2/create/6) so that our engineering team can investigate this further? In the ticket, it would be helpful if you can include report IDs for an advertised product report (version 3) and a product ad report (version 2) so the team can compare.

**Comment by tonisantes** [comment]
@elizafarley I tried but I don't have access to this Jira. How can I get access to be able to open a ticket?

**Comment by elizafarley** [comment]
The person on your team who applied for the API should have received an email from jira@amzn-clicks.atlassian.net with the link to create a JIRA account. If you can find that email, you should be able to make an account. If not, you can raise a ticket in the [advertising console support center](jira@amzn-clicks.atlassian.net) to get added.

**Comment by tonisantes** [comment]
@elizafarley I already opened a Jira ticket. Thank you for your help.

**Comment by elizafarley** [comment]
To circle back, I've updated [the docs](https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#group-by-advertiser) to show `adCreativeStatus` as the only filter for `spAdvertisedProduct` reports. Hopefully that clears up confusion in the future, and thanks again for reporting this issue!
