### ISSUE TITLE
searchTermImpressionRank, searchTermImpressionShare are not removed from metrics of the reporting APIs

### ISSUE THREAD

**Issue by hung-datadive** [amzn/ads-advanced-tools-docs#76]
**Describe the bug**
searchTermImpressionRank, searchTermImpressionShare are still mentioned even though the metrics are no longer available in both v2/v3 report APIs.

**URL of the content**
1. Keyword reports => Available metrics => Sponsored Brands (version 3)
https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#available-metrics-6

2. Search term reports => Available metrics => Sponsored Brands (version 3)
https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#available-metrics-6

**Description of what the documentation should say**
The metrics, searchTermImpressionRank, searchTermImpressionShare, should be removed from the document of the reporting APIs. With that, developers are not confused whether the metrics can be retrieved with Advertising Report APIs

**Screenshots**
1. Keyword reports
<img width="927" alt="image" src="https://user-images.githubusercontent.com/123790267/233651130-a1575f82-db00-4d5b-9db0-3416f9b57d22.png">

2. Search term reports
<img width="742" alt="image" src="https://user-images.githubusercontent.com/123790267/233651346-4e6149d5-0140-444b-9cf1-fe33e875ee59.png">

**Comment by elizafarley** [comment]
Hi @hung-datadive,`searchTermImpressionShare` and `searchTermImpressionRank` should work in the SB search term and keyword reports for reporting version 2. 

The reference to "Sponsored Brands (version 3)" in the above screenshots has to do with whether certain metrics are available for campaigns created using the [Sponsored Brands version 3 campaign management APIs](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/v4-migration-guide). There is no relation to the [version 3 reporting API](https://advertising.amazon.com/API/docs/en-us/reporting/v3/migration-guide). 

Let me know if that resolves your question!

**Comment by hung-datadive** [comment]
@elizafarley I tried with v2/v3 reporting but no luck. Later I came across a note which convinced me impressionShare/impressionRank were unavailable with the reporting APIs. Perhaps the team can add some descriptions about impressionShare/impressionRank to the note to clear confusion.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/123790267/233691071-62e54e29-dd22-43a9-bfa0-511aa0a096f9.png">
Link: https://advertising.amazon.com/API/docs/en-us/reporting/v2/advertising-console#unsupported-report-types

Another suggestion is to add the catch of v3 SB campaign management APIs in [the metric page](https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#available-metrics-6). It's very hard to tell the metrics are available only for campaigns created with v3 SB campaign management. My initial thought was "the metrics can be retrieved with v3 SB reporting."

Link: https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#search-term-reports
![image](https://user-images.githubusercontent.com/123790267/233692684-2908e468-97c6-4ba4-8d30-df74550f2c66.png)


Not sure if you can help. This was the request payload of v2 reporting for a SB keyword report. I didn't receive any `searchTermImpressionRank, searchTermImpressionShare` in the downloaded report.

```
POST https://advertising-api.amazon.com/v2/hsa/keywords/report
Content-Type: application/json
Authorization: Bearer {{amzToken}}
Amazon-Advertising-API-ClientId: {{amzClientId}}
Amazon-Advertising-API-Scope: {{amzProfileId}}

{
  "reportDate": "20230305",
  "metrics": "adGroupId,adGroupName,applicableBudgetRuleId,applicableBudgetRuleName,attributedConversions14d,attributedConversions14dSameSKU,attributedDetailPageViewsClicks14d,attributedOrderRateNewToBrand14d,attributedOrdersNewToBrand14d,attributedOrdersNewToBrandPercentage14d,attributedSales14d,attributedSales14dSameSKU,attributedSalesNewToBrand14d,attributedSalesNewToBrandPercentage14d,attributedUnitsOrderedNewToBrand14d,attributedUnitsOrderedNewToBrandPercentage14d,campaignBudget,campaignBudgetType,campaignId,campaignName,campaignRuleBasedBudget,campaignStatus,clicks,cost,dpv14d,impressions,keywordBid,keywordId,keywordStatus,keywordText,matchType,searchTermImpressionRank,searchTermImpressionShare,unitsSold14d,attributedBrandedSearches14d",
  "creativeType": "all"
}

=======================

// one of the keywords in the downloaded report
  {
    "keywordId": 14424112xxx,
    "matchType": "EXACT",
    "attributedOrdersNewToBrandPercentage14d": 0,
    "attributedDetailPageViewsClicks14d": 0,
    "adGroupId": 14424357xxx,
    "keywordBid": 0.9,
    "keywordStatus": "Enabled",
    "attributedOrderRateNewToBrand14d": 0,
    "attributedConversions14d": 0,
    "campaignBudgetType": "daily",
    "campaignStatus": "enabled",
    "attributedSalesNewToBrandPercentage14d": 0,
    "attributedUnitsOrderedNewToBrandPercentage14d": 0,
    "attributedSalesNewToBrand14d": 0,
    "cost": 0.53,
    "adGroupName": "some ad group",
    "campaignId": 144199888580517920,
    "attributedSales14dSameSKU": 0,
    "impressions": 93,
    "attributedBrandedSearches14d": 0,
    "keywordText": "some keyword",
    "campaignBudget": 3,
    "dpv14d": 0,
    "unitsSold14d": 0,
    "attributedConversions14dSameSKU": 0,
    "clicks": 1,
    "attributedOrdersNewToBrand14d": 0,
    "attributedUnitsOrderedNewToBrand14d": 0,
    "attributedSales14d": 0,
    "campaignName": "some campaign name"
  },
```

**Comment by elizafarley** [comment]
I see where your confusion is coming from. The note on SP/SB Search Term Impression Share report is in reference to the report of same name in the advertising console. You cannot replicate this report using the API at this time.

However, the two metrics should be available for SB reports in V2. If you are not seeing them in the final report, I recommend [opening a JIRA support ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) as it may be a technical bug. 

I also appreciate your feedback on how to better display the supported metrics for SB V3 vs. V4. The team is currently working on adding support for SB in version 3 reporting, and the documentation should be much cleaner.

**Comment by hung-datadive** [comment]
@elizafarley thank you. I'll open a jira ticket. Please close this issue if it's not valid anymore.
