### ISSUE TITLE
Missing required adGroupId field in /sp/campaignNegativeTargets/list

### ISSUE THREAD

**Issue by vitamon** [amzn/ads-advanced-tools-docs#77]
this api response needs to have adGroupId field in the docs. It is exists in the actual responses.

https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#/CampaignNegativeTargetingClauses/ListSponsoredProductsCampaignNegativeTargetingClauses

**Comment by elizafarley** [comment]
Hi @vitamon, could you confirm you are seeing this behavior for **campaign-level** negative targeting clauses? 

Note that we support both campaign-level negative targeting and ad group-level negative targeting. `adGroupId` is expected to be present when using ad group-level targeting ([POST /sp/negativeTargets/list](https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#/NegativeTargetingClauses/ListSponsoredProductsNegativeTargetingClauses)), but would not be expected when using campaign-level product targeting ([POST /sp/campaignNegativeTargets/list](https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#/CampaignNegativeTargetingClauses/ListSponsoredProductsCampaignNegativeTargetingClauses)).

**Comment by vitamon** [comment]
Thank you for quick response. Indeed, everything is ok in the docs.
