### ISSUE TITLE
Cannot consume content type (code: 415) (sb/negativeTargets/list & sb/targets/list ...)

### ISSUE THREAD

**Issue by mgraph** [amzn/ads-advanced-tools-docs#78]
I'm having issue with Sponsored Brands product targeting endpoints above, the Accept Header is not working not matter what type I use (e.g. application/vnd.sblistnegativetargetsresponse.v3.2+json ...)

https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi#/Negative%20product%20targeting/listNegativeTargets

**Comment by elizafarley** [comment]
HI @mgraph,

This request is working for me for POST /sb/targets/list:

```
curl --location 'https://advertising-api.amazon.com/sb/targets/list' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxxx' \
--header 'Authorization: Bearer xxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxx' \
--header 'Content-Type: application/json' \
--data '{}'
```

**Comment by mgraph** [comment]
Thanks @elizafarley 

These two are totally different from other endpoints they use a different filter structure and different header (i.e. Accept should be "application/json" whereas other SB endpoint require Accept header to match the content-type

Dev team should consider consistency across all API

**Comment by elizafarley** [comment]
Just a note, the `Accept` header does take the version value as well. 

For example, this call also works for me:

```
curl --location 'https://advertising-api.amazon.com/sb/targets/list' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxxxxx' \
--header 'Authorization: Bearer Atza|xxxxxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxxx' \
--header 'Accept: application/vnd.sblisttargetsresponse.v3.2+json' \
--header 'Content-Type: application/json' \
--data '{}'
```

I do understand your comment on inconsistency with other APIs. I'll pass this feedback on to the product team for consideration in future versions. Thank you!
