### ISSUE TITLE
 Amazon Ads API Service Desk is not accessible

### ISSUE THREAD

**Issue by hung-datadive** [amzn/ads-advanced-tools-docs#79]
**Describe the bug**
The link of API Service Desk (https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2) is not accessible even though I already accepted the invitation from, jira@amzn-clicks.atlassian.net

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/info/support

**Screenshots**
<img width="940" alt="image" src="https://user-images.githubusercontent.com/123790267/235421608-f18eb356-ae12-40ae-892d-094dda158819.png">

**Additional context**
I can access another portal of Advertising APIs (https://amzn-clicks.atlassian.net/servicedesk/customer/portals). However, this portal is limited to onboarding/registration help. I cannot ask technical questions, or submit API bugs  there.
![image](https://user-images.githubusercontent.com/123790267/235421697-b5b1c5b4-3150-4977-8a00-c7a5d464f418.png)

**Comment by elizafarley** [comment]
Hi @hung-datadive, sorry you are running into this issue! Since you are able to access to the API onboarding JIRA, can you create a ticket there and include your email address? From there, we can add you to the general service desk JIRA.

**Comment by hung-datadive** [comment]
@elizafarley not yet. I followed your advice, and opened a ticket, [AO-13489](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/9/AO-13489). There has been no response so far.

**Comment by elizafarley** [comment]
@hung-datadive Thanks for sharing. Please see if you are able to access now.

**Comment by hung-datadive** [comment]
I have the access now. Thank you!
