### ISSUE TITLE
The "unitsSold14d" field is missing from the downloaded data.

### ISSUE THREAD

**Issue by duwenice** [amzn/ads-advanced-tools-docs#93]
Report Request:
curl --location 'https://advertising-api.amazon.com/v2/hsa/campaigns/report'
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.7e2dc1e5eee04eab99e84f84305ab44c'
--header 'Amazon-Advertising-API-Scope: 2368768247678785'
--header 'Content-Type: application/json'
--data '{
"reportDate":"20230501",
"metrics":"campaignId,campaignName,impressions,clicks,cost,attributedSales14d,attributedConversions14d,unitsSold14d"
}

Received ReportId:
{"reportId":"amzn1.clicksAPI.v1.p1.64770154.aba44b77-4e10-4086-bb16-82ef001968e7","recordType":"campaign","status":"IN_PROGRESS","statusDetails":"Report is being generated."}

Translation of the missing field:
The "unitsSold14d" field is missing from the downloaded data.

some of the response is:
{"unitsSold14d":0,"cost":0,"attributedConversions14d":0,"campaignId":144158449488730278,"clicks":0,"impressions":0,"attributedSales14d":0,"campaignName":"xxxx"},
{"cost":0,"attributedConversions14d":0,"campaignId":188030107477314,"clicks":0,"impressions":0,"attributedSales14d":0,"campaignName":"xxxxx"},

**Comment by elizafarley** [comment]
Hi @duwenice, the `unitsSold14d` metric is only available for non-video campaigns built using the [version 3 API](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod#/Campaigns). If your campaign was build using [version 4](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi#/Campaigns) or contains video ads, you won't get a value for `unitsSold14d`. 

You can view more details on which metrics are supported for each in the [reporting docs](https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#available-metrics). Let me know if that helps!

**Comment by duwenice** [comment]
188030107477314 this campaign is non-video, but still not get a value for unitsSold14d

**Comment by elizafarley** [comment]
Is it possible it's a non-video campaign, but built using the version 4 API? You can check this by calling [POST /sb/v4/campaigns/list](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod#/Campaigns/ListSponsoredBrandsCampaigns) and seeing whether that campaign shows `"isMultiAdGroupEnabled": true`. In that case, `unitsSold14d` would not be available for that campaign.

If you confirm that campaign is `"isMultiAdGroupEnabled": false`, it would indicate a technical bug, and I'd suggest opening a [JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2/create/6).

**Comment by duwenice** [comment]
What does isMultiAdGroupEnabled mean? What is multiadgroup?

**Comment by stevieamazon21** [comment]
hi @duwenice ,

multiadGroup enabled campaigns are a "new" type Sponsored Brands campaigns (SBv4) where you can create multiple adGroups.  Prior, Sponsored Brands campaigns were limited to a single adGroup.  The reference documentation for SBv4 campaigns can be found here, https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod#/Campaigns, and the release notes describing this feature can be found here, https://advertising.amazon.com/API/docs/en-us/info/release-notes#sponsored-brands-ad-groups-are-now-available-in-open-beta-through-amazon-ads-api.  Cheers!

-Steve

**Comment by elizafarley** [comment]
@duwenice Were you able to resolve this issue using the above explanation? I'm going to resolve the issue for now, but please reopen if needed.
