### ISSUE TITLE
Issue Report: /en-us/onboarding/apply-for-access

### ISSUE THREAD

**Issue by Chris04200** [amzn/ads-advanced-tools-docs#95]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**

**URL of the content**
Provide the advanced tools center or GitHub URL where you see the bug.

**Description of what the documentation currently says**
Describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
A clear and concise description of the guidance you expected to see in the documentation.

**Screenshots**

**Additional context**

**Comment by elizafarley** [comment]
Hi @Chris04200, did you see an issue on this page: https://advertising.amazon.com/API/docs/en-us/onboarding/apply-for-access? If yes, please provide details so we can help. Thanks!

**Comment by jerirose** [comment]
@Chris04200 we'll close this issue for now. If you can provide more detail on the issue, please feel free to reopen this ticket!
