### ISSUE TITLE
Issue Report: sponsor brand report generating

### ISSUE THREAD

**Issue by utsavvasoya** [amzn/ads-advanced-tools-docs#98]
If you need help troubleshooting a problem with the Amazon Ads API, visit the [Amazon Ads API service desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2). Issues are for reporting documentation bugs and requesting enhancements only.

**Describe the bug**

**URL of the content**
Provide the advanced tools center or GitHub URL where you see the bug.

**Description of what the documentation currently says**
Describe the section/paragraph of the documentation where you see the bug.

**Description of what the documentation should say**
I am not able to generate report for sponsor brands with spend and sales field can you please provide me more information about this API .

**Screenshots**

**Additional context**

**Comment by elizafarley** [comment]
HI @utsavvasoya, which type of Sponsored Brands report are you trying to generate? Can you share a sample call that you are trying?

**Comment by elizafarley** [comment]
Hopefully I answered your question in this discussion: https://github.com/amzn/ads-advanced-tools-docs/discussions/99. Closing this as a duplicate, and we can use the discussion if you need more info.
